// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type RegisterResponse struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	User_id     int64  `json:"user_id"`
	Token       string `json:"token"`
}

type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	User_id     int64  `json:"user_id"`
	Token       string `json:"token"`
}

type UserInfoRequest struct {
	User_id int64  `json:"user_id"`
	Token   string `json:"token"`
}

type UserInfoResponse struct {
	Status_code int32  `json:"status_code"`
	Status_msg  string `json:"status_msg"`
	User        User   `json:"user"`
}

type User struct {
	Id             int64  `json:"id"`
	Name           string `json:"name"`
	Follow_count   int    `json:"follow_count"`
	Follower_count int    `json:"follower_count"`
}
